---
pipeline:
  lint:
    image: golangci/golangci-lint:v1.21.0
    group: ci
    commands:
      - golangci-lint run
  build:
    image: golang:1.13
    group: ci
    commands:
      - make build

branches:
  - master
  - feature/*
