---
pipeline:
  dependencies:
    image: golang:1.13
    secrets: [ snyk_token ]
    group: ci
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install -g snyk
      - snyk test
    when:
      branch: master
      event: push
  lint:
    image: golangci/golangci-lint:v1.21.0
    group: ci
    commands:
      - make lint
  build:
    image: golang:1.13
    group: ci
    commands:
      - make build

branches:
  - master
  - feature/*
