version: '3.4'

services:
  mongod1:
    hostname: mongod1.internal
    image: mongodb/apix_test:mongod
    volumes:
      - mongo-data:/data/db
    ports:
      - "37017:27017"

  mongot1:
    hostname: mongot1
    image: mongodb/apix_test:mongot
    volumes:
      - mongot-data-1:/var/lib/mongot
      - mongot-metrics-1:/var/lib/mongot/metrics
    # ports:
    #   - "27027:27027"
    #   - "5006:5006"
  mms:
    hostname: mms
    image: mongodb/apix_test:mms
    environment:
      - 'MONGOT_HOSTS={"rs0": ["mongot1"]}'
    volumes:
      - "~/Library/Application Support/atlascli:/etc/mms"
    # ports:
    #   - "31313:31313"
    #   - "31314:31314"
    #   - "5007:5007"

volumes:
  mongo-data:
  mongot-data-1:
  mongot-metrics-1:
